Problem: Django cache directory should be owned by www-data
Otherwise you get errors like these:

```
IOError: [Errno 13] Permission denied: '/var/tmp/django_cache/96b2eeef9dbbd9d34340463b78cbd10b.djcache'
```

Solution: Set the correct permissions. Also create this directory if it
doesn't exist.