Fix parse error for celeryd init script
The celeryd cli does not support indexing by worker name, when there is only
one worker so "-c:workername-with-hyphen 3"  would result in:
ValueError: invalid literal for int() with base 10: 'workername'

Seems like a celeryd bug, multi should support 1 or more workers..